"""
test_folder_names.py
Checks that the folder names generated by the new taxonomy system match existing folders in parts/.
Currently validates countersunk (hex_head/black) and socket_cap (hex_head/black),
which are the two types that already have folders on disk.
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from working_oomp_populate_countersunk import generate as gen_countersunk
from working_oomp_populate_socket_cap import generate as gen_socket_cap

PARTS_DIR = os.path.join(os.path.dirname(__file__), "..", "parts")
TAXONOMY_1 = "hardware"
TAXONOMY_2 = "screw"


def _build_folder_name(option):
    parts = [TAXONOMY_1, TAXONOMY_2]
    for key in ["taxonomy_3", "taxonomy_4", "taxonomy_5", "taxonomy_6", "taxonomy_7"]:
        val = option.get(key, "")
        if val:
            parts.append(val)
    return "_".join(parts)


def _existing_folders():
    return set(os.listdir(PARTS_DIR))


# ── countersunk hex_head black ────────────────────────────────────────────────

class TestCountersunkHexHeadBlack:
    def setup_method(self):
        self.options = gen_countersunk()
        self.existing = _existing_folders()

    def test_all_generated_folders_exist_on_disk(self):
        missing = []
        for opt in self.options:
            name = _build_folder_name(opt)
            if name not in self.existing:
                missing.append(name)
        assert missing == [], f"Folders expected on disk but missing:\n" + "\n".join(missing)

    def test_no_extra_countersunk_hex_black_folders_on_disk(self):
        """Every countersunk_hex_head_black folder on disk should be generated."""
        prefix = f"{TAXONOMY_1}_{TAXONOMY_2}_countersunk_hex_head_black_"
        on_disk = {f for f in self.existing if f.startswith(prefix)}
        generated = {_build_folder_name(o) for o in self.options}
        extra = on_disk - generated
        assert extra == set(), f"Folders on disk not covered by generate():\n" + "\n".join(sorted(extra))


# ── socket_cap hex_head black ─────────────────────────────────────────────────

class TestSocketCapHexHeadBlack:
    def setup_method(self):
        self.options = gen_socket_cap()
        self.existing = _existing_folders()

    def test_all_generated_folders_exist_on_disk(self):
        missing = []
        for opt in self.options:
            name = _build_folder_name(opt)
            if name not in self.existing:
                missing.append(name)
        assert missing == [], f"Folders expected on disk but missing:\n" + "\n".join(missing)

    def test_no_extra_socket_cap_hex_black_folders_on_disk(self):
        """Every socket_cap_hex_head_black folder on disk should be generated."""
        prefix = f"{TAXONOMY_1}_{TAXONOMY_2}_socket_cap_hex_head_black_"
        on_disk = {f for f in self.existing if f.startswith(prefix)}
        generated = {_build_folder_name(o) for o in self.options}
        extra = on_disk - generated
        assert extra == set(), f"Folders on disk not covered by generate():\n" + "\n".join(sorted(extra))


# ── cross-type duplicate check ────────────────────────────────────────────────

def test_no_cross_type_duplicates():
    """No two generators should produce the same folder name."""
    from working_oomp_populate_countersunk_pozi import generate as gen_countersunk_pozi
    from working_oomp_populate_countersunk_philips import generate as gen_countersunk_philips
    from working_oomp_populate_socket_cap_low_head import generate as gen_socket_cap_low_head
    from working_oomp_populate_socket_cap_low_head_ultra import generate as gen_socket_cap_low_head_ultra
    from working_oomp_populate_flat_head import generate as gen_flat_head
    from working_oomp_populate_button_head import generate as gen_button_head
    from working_oomp_populate_grub import generate as gen_grub
    from working_oomp_populate_machine_screw import generate as gen_machine_screw
    from working_oomp_populate_self_tapping import generate as gen_self_tapping
    from working_oomp_populate_thread_forming import generate as gen_thread_forming
    from working_oomp_populate_wood import generate as gen_wood

    all_gens = [
        gen_countersunk, gen_countersunk_pozi, gen_countersunk_philips,
        gen_socket_cap, gen_socket_cap_low_head, gen_socket_cap_low_head_ultra,
        gen_flat_head, gen_button_head, gen_grub, gen_machine_screw,
        gen_self_tapping, gen_thread_forming, gen_wood,
    ]

    seen = {}
    for gen in all_gens:
        for opt in gen():
            name = _build_folder_name(opt)
            assert name not in seen, (
                f"Duplicate folder name across generators: '{name}'\n"
                f"First seen from: {seen[name]}\n"
                f"Also produced by: {gen.__module__}"
            )
            seen[name] = gen.__module__
